# Generated by Django 5.1.7 on 2026-06-17 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drift_score', models.FloatField()),
                ('is_drift_detected', models.BooleanField(default=True)),
                ('reference_count', models.IntegerField(default=50)),
                ('current_count', models.IntegerField(default=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drifts', to='app.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('prediction_text', models.TextField()),
                ('response_time_ms', models.PositiveIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='app.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
