# Generated by Django 5.1.4 on 2026-08-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_object_storage_and_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('key_decisions', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('full_transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_analysis', to='app.ingestedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
